# Generated by Django 2.0.7 on 2018-07-13 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('ocupação', models.CharField(max_length=50, verbose_name='Ocupação')),
                ('tipo', models.CharField(choices=[('P', 'Pessoal'), ('C', 'Comercial')], max_length=1, verbose_name='Tipo')),
            ],
        ),
        migrations.CreateModel(
            name='ContatoEndereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Contato')),
            ],
        ),
        migrations.CreateModel(
            name='ContatoTelefone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Contato')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Departamento')),
            ],
            options={
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='DepartamentoEndereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='DepartamentoTelefone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=50, verbose_name='País')),
                ('estado', models.CharField(max_length=30, verbose_name='Estado')),
                ('cidade', models.CharField(max_length=50, verbose_name='Cidade')),
                ('logradouro', models.CharField(max_length=100, verbose_name='Logradouro')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('complemento', models.CharField(max_length=10, verbose_name='Complemento')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
            ],
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Instituição')),
            ],
            options={
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='InstituicaoEndereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Endereco')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Instituicao')),
            ],
        ),
        migrations.CreateModel(
            name='InstituicaoTelefone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Instituicao')),
            ],
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, verbose_name='Telefone')),
            ],
        ),
        migrations.AddField(
            model_name='instituicaotelefone',
            name='telefone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Telefone'),
        ),
        migrations.AddField(
            model_name='departamentotelefone',
            name='telefone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Telefone'),
        ),
        migrations.AddField(
            model_name='departamentoendereco',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Endereco'),
        ),
        migrations.AddField(
            model_name='contatotelefone',
            name='telefone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Telefone'),
        ),
        migrations.AddField(
            model_name='contatoendereco',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Endereco'),
        ),
    ]
