# Generated by Django 2.0.7 on 2018-07-13 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_notas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='ocupação',
            new_name='ocupacao',
        ),
    ]
