# Generated by Django 2.0.7 on 2018-07-13 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20180713_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContatoEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='notas',
            name='usuario',
        ),
        migrations.AddField(
            model_name='contato',
            name='notas',
            field=models.TextField(default='', verbose_name='Nota'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Notas',
        ),
        migrations.AddField(
            model_name='contatoemail',
            name='contato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Contato'),
        ),
        migrations.AddField(
            model_name='contatoemail',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Email'),
        ),
    ]
