# Generated by Django 2.0.7 on 2018-07-16 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0006_auto_20180716_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(blank=True, verbose_name='Descição')),
            ],
        ),
        migrations.CreateModel(
            name='InteracaoContatos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Contato')),
                ('interacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interaction.Interacao')),
            ],
        ),
    ]
