# Generated by Django 2.0.7 on 2018-07-16 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interacao',
            name='data',
            field=models.DateField(default='2018-06-21', verbose_name='Data'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interacao',
            name='horario',
            field=models.TimeField(default='12:00', verbose_name='Horário'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interacao',
            name='resumo',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Resumo'),
        ),
        migrations.AlterField(
            model_name='interacao',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
    ]
