# Generated by Django 2.0.7 on 2018-07-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0002_auto_20180716_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interacao',
            name='horario',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário'),
        ),
    ]
